# Day - 11
---

# Pandas
> This note explains ...
 1. Install Libraries
    > pip install pandas \
    > pip install numpy

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Object creation
s = pd.Series([1, 3, 5,np.nan, 7, 8, 9])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    7.0
5    8.0
6    9.0
dtype: float64

In [8]:
dates = pd.date_range('20260905', periods=6)
dates

DatetimeIndex(['2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08',
               '2026-09-09', '2026-09-10'],
              dtype='datetime64[us]', freq='D')

In [10]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601
2026-09-08  0.052734  1.372165  1.016981 -0.345541
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653
2026-09-10 -0.969725  0.548520  0.845305 -1.333559

In [14]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20260905'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["girl", "woman", "girl", "woman"]),
                    'F': 'Females'})
df2

     A          B    C  D      E        F
0  1.0 2026-09-05  1.0  3   girl  Females
1  1.0 2026-09-05  1.0  3  woman  Females
2  1.0 2026-09-05  1.0  3   girl  Females
3  1.0 2026-09-05  1.0  3  woman  Females

In [15]:
print(df2.dtypes)

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [16]:
df.head(3)

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601

In [17]:
df.tail(2)

                   A         B         C         D
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653
2026-09-10 -0.969725  0.548520  0.845305 -1.333559

In [18]:
df.index

DatetimeIndex(['2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08',
               '2026-09-09', '2026-09-10'],
              dtype='datetime64[us]', freq='D')

In [21]:
df.to_numpy()

array([[ 1.09191421,  0.62803628, -2.1952264 ,  1.06305339],
       [ 0.03430524, -0.0760335 , -0.87871736,  0.20379371],
       [ 0.36468567, -0.85693395, -0.96420358, -0.87960101],
       [ 0.05273399,  1.3721651 ,  1.01698079, -0.34554132],
       [ 1.37804924, -0.40553111, -0.20976058, -0.9036526 ],
       [-0.96972477,  0.54851985,  0.84530517, -1.33355872]])

In [22]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.325327  0.201704 -0.397604 -0.365918
std    0.840665  0.804811  1.213681  0.878214
min   -0.969725 -0.856934 -2.195226 -1.333559
25%    0.038912 -0.323157 -0.942832 -0.897640
50%    0.208710  0.236243 -0.544239 -0.612571
75%    0.910107  0.608157  0.581539  0.066460
max    1.378049  1.372165  1.016981  1.063053

In [24]:
df.T  # To take the trasnpose of the data frame

   2026-09-05  2026-09-06  2026-09-07  2026-09-08  2026-09-09  2026-09-10
A    1.091914    0.034305    0.364686    0.052734    1.378049   -0.969725
B    0.628036   -0.076033   -0.856934    1.372165   -0.405531    0.548520
C   -2.195226   -0.878717   -0.964204    1.016981   -0.209761    0.845305
D    1.063053    0.203794   -0.879601   -0.345541   -0.903653   -1.333559

In [25]:
df.sort_index(axis=1, ascending=True)  # To sort the data frame by axis

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601
2026-09-08  0.052734  1.372165  1.016981 -0.345541
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653
2026-09-10 -0.969725  0.548520  0.845305 -1.333559

In [26]:
df.sort_values(by='B')  # To sort the data frame by values

                   A         B         C         D
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-10 -0.969725  0.548520  0.845305 -1.333559
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-08  0.052734  1.372165  1.016981 -0.345541

In [27]:
df['A']  # To select a single column, which yields a Series, equivalent to df.A

2026-09-05    1.091914
2026-09-06    0.034305
2026-09-07    0.364686
2026-09-08    0.052734
2026-09-09    1.378049
2026-09-10   -0.969725
Freq: D, Name: A, dtype: float64

In [28]:
df[0:3]  # Selecting via [], which slices the rows.

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601

In [ ]:
df[:5] # Selecting via [], which slices the rows.

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601
2026-09-08  0.052734  1.372165  1.016981 -0.345541
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653

In [32]:
df[0:3]

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601

In [ ]:
df.loc[dates[0]] #row wise selection using loc

A    1.091914
B    0.628036
C   -2.195226
D    1.063053
Name: 2026-09-05 00:00:00, dtype: float64

In [34]:
df.loc[:, ['A', 'B']] #column wise selection using loc

                   A         B
2026-09-05  1.091914  0.628036
2026-09-06  0.034305 -0.076033
2026-09-07  0.364686 -0.856934
2026-09-08  0.052734  1.372165
2026-09-09  1.378049 -0.405531
2026-09-10 -0.969725  0.548520

In [36]:
df.at[dates[2], 'A']  # Access a single value for a row/column label pair

np.float64(0.36468566917905293)

In [37]:
df[df['A'] > 0]  # Selecting values from a DataFrame where a boolean condition is met

                   A         B         C         D
2026-09-05  1.091914  0.628036 -2.195226  1.063053
2026-09-06  0.034305 -0.076033 -0.878717  0.203794
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601
2026-09-08  0.052734  1.372165  1.016981 -0.345541
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653

In [38]:
df[df>0]  # Selecting values from a DataFrame where a boolean condition is met

                   A         B         C         D
2026-09-05  1.091914  0.628036       NaN  1.063053
2026-09-06  0.034305       NaN       NaN  0.203794
2026-09-07  0.364686       NaN       NaN       NaN
2026-09-08  0.052734  1.372165  1.016981       NaN
2026-09-09  1.378049       NaN       NaN       NaN
2026-09-10       NaN  0.548520  0.845305       NaN

In [39]:
# Isin() method is used to filter data frames based on a list of values. It returns a boolean Series indicating whether each element in the DataFrame is contained in the list of values.
df[df['A'].isin([0, 2])]  # Selecting values from a DataFrame where a boolean condition is met

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [41]:
# adding another column to the data frame
df['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df

                   A         B         C         D      E
2026-09-05  1.091914  0.628036 -2.195226  1.063053    one
2026-09-06  0.034305 -0.076033 -0.878717  0.203794    one
2026-09-07  0.364686 -0.856934 -0.964204 -0.879601    two
2026-09-08  0.052734  1.372165  1.016981 -0.345541  three
2026-09-09  1.378049 -0.405531 -0.209761 -0.903653   four
2026-09-10 -0.969725  0.548520  0.845305 -1.333559  three